### ISSUE TITLE
ClearNewRecords() not removing?

### ISSUE THREAD

**Issue by ritdaw** [MxLabs/Anviz#25]
The ClearNewRecords() is not clearing the records on my W1 (non pro). Using 2.0.1. 
Can you confirm the difference between clearing and deleting?

```
var records = await device.DownloadRecords(true); //true to get only new records
foreach (var rec in records)
{
	Console.WriteLine($"Employee {dict[rec.UserCode]} at {rec.DateTime.ToLongDateString()} {rec.DateTime.ToLongTimeString()}");
}
await device.ClearNewRecords();
var stats = await device.GetDownloadInformation();
Console.WriteLine($"TotalUsers {stats.UserAmount} TotalRecords {stats.AllRecordAmount}");
```

Output:
```
TotalUsers 1 TotalRecords 2
```

**Comment by ritdaw** [comment]
This appears to be a non issue, the "Record List" shows all previous entries despite not actually being on the device.

**Comment by JohnKiller** [comment]
Anviz devices internally have a pointer to the last downloaded record. When you call `DownloadRecords` with `true`, you get all the records from this pointer to the last record. Ideally at this point your application will do whatever wants to do with this information, and when successfully saved the data to db or whatever, you call `ClearNewRecords` so the pointer now points to the last record. A new call to `DownloadRecords` will yield nothing.

What's the point, you may ask. This is because if you application crashes or fails to save the data before calling clear, you have the chance to run again your script to parse again the records.

However, storage is limited (in W1 to 100000 records) so instead of calling `ClearNewRecords` you can permanently delete them all. It's up to you. You can also periodically purge them.

Hope this helps, feel free to ask more if you need.

**Comment by JohnKiller** [comment]
Also I should add that `ClearNewRecords` accepts a number as parameter. This is because it may happen that a new record is registered from a user while you are processing the data.

In this case you should call the function with the number of records you have effectively written to db. The pointer advances this number of times

**Comment by ritdaw** [comment]
Got it, excellent explanation!

**Comment by ritdaw** [comment]
We might for example purge records out of hours and when record count is high

```
//if out of hours and record count is high, delete records
if (stats.AllRecordAmount > 60000 && DateTime.Now.Hour == 23)
	await device.DeleteAllRecords();
```
